# Generated by Django 4.2.6 on 2023-10-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.IntegerField(null=True),
        ),
    ]
