# Generated by Django 4.2.6 on 2023-10-13 00:42

import cards.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pin',
            field=models.CharField(default=cards.models.random_pin, max_length=4, validators=[django.core.validators.RegexValidator(message='El campo debe contener exactamente 4 dígitos.', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiring_date',
            field=models.DateTimeField(default=cards.models.get_expiring_date),
        ),
    ]
