# Generated by Django 4.2.6 on 2023-10-14 19:48

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='alias',
            field=models.CharField(default=cards.models.random_alias, max_length=100, unique=True),
        ),
    ]
