# Generated by Django 4.2.6 on 2023-11-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_pin_alter_transaction_receiver_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_card',
            field=models.ForeignKey(default=1000000000000001, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reciver', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_card',
            field=models.ForeignKey(default=1000000000000001, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender', to='cards.card'),
        ),
    ]
